# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=140)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('team', models.CharField(max_length=5)),
                ('score', models.FloatField()),
            ],
        ),
    ]
