# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
