# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 01:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('lastScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('publishedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField()),
                ('scoreList', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('associatedTags', models.TextField()),
                ('name', models.CharField(max_length=5)),
                ('longName', models.CharField(max_length=30)),
                ('homeColourRed', models.IntegerField()),
                ('homeColourBlue', models.IntegerField()),
                ('homeColourGreen', models.IntegerField()),
                ('awayColourRed', models.IntegerField()),
                ('awayColourBlue', models.IntegerField()),
                ('awayColourGreen', models.IntegerField()),
                ('league', models.CharField(max_length=30)),
                ('nextGame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
