# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20170618_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='awayColourBlue',
        ),
        migrations.RemoveField(
            model_name='team',
            name='awayColourGreen',
        ),
        migrations.RemoveField(
            model_name='team',
            name='awayColourRed',
        ),
        migrations.RemoveField(
            model_name='team',
            name='homeColourBlue',
        ),
        migrations.RemoveField(
            model_name='team',
            name='homeColourGreen',
        ),
        migrations.RemoveField(
            model_name='team',
            name='homeColourRed',
        ),
        migrations.AddField(
            model_name='team',
            name='awayColour',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='homeColour',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
