# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20170620_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='imagePath',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
