# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 13:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20170624_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='associatedTags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(default='Premier League', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='longName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='scoreList',
            field=models.CharField(max_length=500, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
