# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 15:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20170624_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='scoreList',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
