# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 16:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_player_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='scoreList',
            field=models.CharField(default=b'', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='volumeList',
            field=models.CharField(default=b'', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
